package com.example.mockservice.web;

import com.example.mockservice.domain.MockConfiguration;
import com.example.mockservice.repository.MockConfigurationRepository;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;
import jakarta.servlet.http.HttpServletResponse;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpHeaders;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import java.io.IOException;
import java.util.List;

@Controller
@RequiredArgsConstructor
public class ImportExportController {

    private final MockConfigurationRepository mockConfigurationRepository;
    private final ObjectMapper objectMapper;

    @GetMapping("/export")
    @ResponseBody
    public void exportConfigurations(HttpServletResponse response) throws IOException {
        List<MockConfiguration> configs = mockConfigurationRepository.findAll();

        response.setContentType("application/json");
        response.setHeader(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=mock-configurations.json");

        objectMapper.writeValue(response.getOutputStream(), configs);
    }

    @PostMapping("/import")
    public String importConfigurations(@RequestParam("file") MultipartFile file,
            RedirectAttributes redirectAttributes) {
        if (file.isEmpty()) {
            redirectAttributes.addFlashAttribute("error", "Please select a file to upload");
            return "redirect:/services";
        }

        try {
            List<MockConfiguration> configs = objectMapper.readValue(file.getInputStream(),
                    new TypeReference<List<MockConfiguration>>() {
                    });

            // Validate? Ideally check if operationId exists, but for now we just
            // save/update.
            // A missing operationId implies it won't target anything useful, but it's safe.

            mockConfigurationRepository.deleteAll(); // Strategy: Replace all or Merge? Requirement says "restore
                                                     // settings". Usually implies replace or overlay. I'll
                                                     // overlay/saveAll.
            // Using saveAll will update if ID exists, insert if new.
            // BUT if IDs are UUIDs generated by DB, exporting and importing might cause
            // issues unless IDs are preserved.
            // Since we export the Entity, it has ID.
            mockConfigurationRepository.saveAll(configs);

            redirectAttributes.addFlashAttribute("message", "Configurations imported successfully!");
        } catch (IOException e) {
            redirectAttributes.addFlashAttribute("error", "Import failed: " + e.getMessage());
        }

        return "redirect:/services";
    }
}
